Add label to ConfigMap containing report
This enables operators to easily distinguish between scans.

the specific label that's used is in the following form:

    compliance-scan: $NAME_OF_THE_SCAN

So, if the compliance scan is called "example-compliancescan", the label
will be:

    compliance-scan: example-compliancescan

For instance:

    $ oc get compliancescans
    NAME                      AGE
    example-compliancescan    3m12s
    example-compliancescan2   13s
    $ oc get oc cm
    error: the server doesn't have a resource type "oc"
    $ oc get cm
    NAME                                                       DATA   AGE
    example-compliancescan-ip-10-0-130-199.ec2.internal-pod    1      3m26s
    example-compliancescan-ip-10-0-141-111.ec2.internal-pod    1      3m28s
    example-compliancescan-ip-10-0-149-133.ec2.internal-pod    1      3m28s
    example-compliancescan-ip-10-0-152-6.ec2.internal-pod      1      3m27s
    example-compliancescan-ip-10-0-168-38.ec2.internal-pod     1      3m28s
    example-compliancescan-ip-10-0-172-211.ec2.internal-pod    1      3m29s
    example-compliancescan2-ip-10-0-130-199.ec2.internal-pod   1      39s
    example-compliancescan2-ip-10-0-141-111.ec2.internal-pod   1      39s
    example-compliancescan2-ip-10-0-149-133.ec2.internal-pod   1      41s
    example-compliancescan2-ip-10-0-152-6.ec2.internal-pod     1      41s
    example-compliancescan2-ip-10-0-168-38.ec2.internal-pod    1      41s
    example-compliancescan2-ip-10-0-172-211.ec2.internal-pod   1      40s
    $ oc get cm -l compliance-scan=example-compliancescan
    NAME                                                      DATA   AGE
    example-compliancescan-ip-10-0-130-199.ec2.internal-pod   1      3m41s
    example-compliancescan-ip-10-0-141-111.ec2.internal-pod   1      3m43s
    example-compliancescan-ip-10-0-149-133.ec2.internal-pod   1      3m43s
    example-compliancescan-ip-10-0-152-6.ec2.internal-pod     1      3m42s
    example-compliancescan-ip-10-0-168-38.ec2.internal-pod    1      3m43s
    example-compliancescan-ip-10-0-172-211.ec2.internal-pod   1      3m44s